name: drips_water
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.3.0
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  shared_preferences: ^2.5.3
  cloud_firestore: ^6.0.3
  http: ^1.5.0
  googleapis_auth: ^2.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.jpg"

flutter_native_splash:
  color: "#ffffff"
  image: assets/app_logo.jpg
  android_12:
    image: assets/app_logo.jpg
    color: "#ffffff"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/credentials.json
    - assets/images/onboarding_images/
    - assets/images/splash_screen/
    - assets/images/welcome_screen/
    - assets/images/home_screen/
    - assets/images/order_success/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
